apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs
  namespace: hcp
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: cluster-manager
  resources:
    requests:
      storage: 1Mi
  volumeName: nfs
