apiVersion: v1
kind: PersistentVolume
metadata: 
  name: nfs
spec: 
  capacity:
    storage: 1Mi
  storageClassName: cluster-manager
  accessModes: 
    - ReadWriteMany
  nfs:
    server: 10.0.5.86
    path: "/root/.kube/"
    readOnly: false
