apiVersion: v1
kind: PersistentVolume
metadata:
  name: fedora
  labels:
    app: containerized-data-importer 
spec:
  storageClassName: hostpath
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
     path: "/mnt/data"
