apiVersion: v1
kind: Service
metadata:
  name: testvm-svc
spec:
  type: NodePort
  selector:
    kubevirt.io/name: testvm
  ports:
  - name: test-vm-ssh
    protocol: TCP
    port: 22
    targetPort: 22
   
