apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: 
    - cd /root/
    - mkdir test
    - mount -t nfs 10.0.5.86:/root/.kube/ /root/test
    - cd test
    - ls
   
